# Generated by Django 3.1.7 on 2021-03-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('title', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='')),
                ('location', models.TextField(default='', max_length=30)),
                ('image', models.ImageField(upload_to='images/')),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
