# Generated by Django 3.1.7 on 2021-03-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='image.jpg', upload_to='images/'),
        ),
    ]
